---
- name: new
  hosts: 192.168.122.171
  tasks:
    - name: Updating Project Sync to false pre Gitlab stop
      ansible.controller.project:
        controller_host: 192.168.122.171
        controller_username: admin
        controller_password: ADM
        organization: "Default"
        name: "neww -gitt -amar"
        #scm_type: "git"
        #scm_update_on_launch: true
        #scm_delete_on_update: true
        #fully_managed: false
# https://github.com/sayjoshi/ansible.git
